"""API key authentication, scopes, and rate limiting for /api/v1.

WHAT A KEY IS
-------------
A credential handed to an integration, which then lives in somebody else's configuration
file for a long time. That shapes every decision here: keys are bound to one company so
their reach is obvious, they carry explicit scopes so a read-only integration cannot write,
they can expire, and revoking one takes effect on the next request rather than whenever a
session happens to end.

WHY IT REUSES AdminScope
------------------------
A key's data access is exactly "one company's rows", which is what AdminScope already
expresses and what the whole /api/admin surface is already filtered through. Writing a
second filtering mechanism for /api/v1 would mean two implementations of the same rule,
and the second one is the one that gets a subtle case wrong — silently, because a too-wide
filter still returns a valid-looking response.
"""

import datetime
import hashlib
import hmac
import secrets
import threading

from fastapi import Depends, Header, HTTPException, Request, status

from app.database.db import db
from app.models import ApiKey, User
from app.utils.scope import AdminScope

# Visible marker so a leaked key is recognisable as one — in a log, a paste, a public repo.
# Secret scanners key off prefixes like this, and a key that cannot be recognised is a key
# nobody reports.
KEY_PREFIX = 'sit_'

# 32 bytes from secrets. Brute force is not a threat model at this width; the threat is a
# key being copied, which is what expiry and revocation are for.
KEY_BYTES = 32

# How much of the key is stored in the clear, prefix included. Enough to identify a key in a
# list without being enough to use.
PREFIX_LENGTH = 16


# Every scope the system understands. A key can only be created with scopes from this list,
# so a typo produces an error at creation rather than a permission that silently never
# matches anything.
SCOPES = {
    'candidates:read': 'Read candidate records',
    'candidates:write': 'Update candidate profiles',
    'interviews:read': 'Read interviews and reports',
    'interviews:delete': 'Delete interviews',
    'recordings:read': 'Get playback links for session recordings',
    'proctor_snapshots:read': 'Read proctoring images',
    'invites:send': 'Send interview invitations',
    'reinterview:decide': 'Approve or reject second-interview requests',
    'analytics:read': 'Read aggregate scoring analytics',
    'audit:read': 'Read the audit log',
    'transactions:read': 'Read transactions',
}


def generate_key():
    """A new secret and the prefix stored alongside its hash.

    Returns (full_key, prefix, hash). The full key is returned to the caller ONCE and never
    stored, so this is the only moment it exists anywhere we control.
    """
    full = KEY_PREFIX + secrets.token_urlsafe(KEY_BYTES)
    return full, full[:PREFIX_LENGTH], hash_key(full)


def hash_key(raw):
    """SHA-256, not bcrypt.

    bcrypt is right for passwords because it is slow, which is what defends a low-entropy
    secret a human chose. This secret is 32 random bytes generated by us, so brute force is
    not the threat — and unlike a password it is presented on EVERY request, where ~100ms
    per verification would consume more of a worker than the rest of the request combined.
    """
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()


# ---------------------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------------------

# In-process and per-container, exactly like the login and resume-upload throttles already
# in this app. That is a deliberate limit, not an oversight: it is a brake on a runaway or
# abusive integration, not a distributed quota system, and it resets when the process does.
# A shared limiter would need Redis, which this project does not run.
_RATE_WINDOW = datetime.timedelta(minutes=1)
_rate_hits = {}
_rate_lock = threading.Lock()


def _check_rate_limit(key_id, limit):
    """Refuse the request when this key has spent its allowance for the current minute."""
    now = datetime.datetime.utcnow()
    cutoff = now - _RATE_WINDOW

    with _rate_lock:
        # Sweep spent buckets so the dict cannot grow across a long uptime.
        for k in [k for k, hits in _rate_hits.items() if all(t < cutoff for t in hits)]:
            del _rate_hits[k]

        recent = [t for t in _rate_hits.get(key_id, []) if t >= cutoff]
        if len(recent) >= limit:
            retry_after = int((min(recent) + _RATE_WINDOW - now).total_seconds())
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail=f"Rate limit of {limit} requests per minute exceeded.",
                headers={'Retry-After': str(max(retry_after, 1))},
            )
        recent.append(now)
        _rate_hits[key_id] = recent
        return limit - len(recent)


def reset_rate_limits():
    """Test helper. Nothing in the request path calls this."""
    with _rate_lock:
        _rate_hits.clear()


# ---------------------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------------------

class ApiKeyPrincipal:
    """The authenticated caller behind an API key: who they are and what they may reach."""

    def __init__(self, api_key, scope, remaining):
        self.api_key = api_key
        self.scope = scope
        self.rate_limit_remaining = remaining

    def require(self, *scopes):
        """Refuse unless the key carries EVERY scope named.

        403 rather than 404 here, unlike the row-level checks in AdminScope. The distinction
        is deliberate: a missing scope is a fact about the caller's own key, which they
        already know, so stating it leaks nothing and saves an integration author from
        guessing. A row being out of company reach is a fact about someone else's data, and
        confirming it exists is what makes an id enumerable.
        """
        missing = [s for s in scopes if not self.api_key.has_scope(s)]
        if missing:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"This API key is missing the required scope(s): {', '.join(missing)}."
            )


def _extract_key(request, x_api_key):
    """The presented key, from either accepted place.

    Two forms because integrations differ in what they can send, and an API nobody can
    authenticate against is not more secure, only unused.
    """
    if x_api_key:
        return x_api_key.strip()
    auth = request.headers.get('Authorization') or ''
    if auth.startswith('Bearer '):
        candidate = auth[7:].strip()
        # Only treat a Bearer value as an API key when it looks like one. A JWT sent here
        # must fall through to the ordinary error rather than being hashed and compared,
        # which would otherwise make the failure mode confusing for the caller.
        if candidate.startswith(KEY_PREFIX):
            return candidate
    return None


def api_key_auth(
    request: Request,
    x_api_key: str = Header(default=None, alias='X-API-Key'),
) -> ApiKeyPrincipal:
    """Dependency for every /api/v1 route."""
    presented = _extract_key(request, x_api_key)

    unauthorized = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Provide a valid API key in the X-API-Key header.",
        headers={'WWW-Authenticate': 'Bearer'},
    )

    if not presented or not presented.startswith(KEY_PREFIX):
        raise unauthorized

    record = ApiKey.query.filter_by(key_prefix=presented[:PREFIX_LENGTH]).first()
    if not record:
        raise unauthorized

    # compare_digest rather than ==. Both are hex digests of the same length so the timing
    # signal is small, but the cost of being careful here is one function call.
    if not hmac.compare_digest(record.key_hash, hash_key(presented)):
        raise unauthorized

    if not record.is_active():
        # Says which, because both are states the key's owner can see and fix, and "invalid
        # key" would send them hunting for a typo in a key that is simply switched off.
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"This API key has been {record.status()}."
        )

    remaining = _check_rate_limit(record.id, record.rate_limit_per_minute or 60)

    # Best effort, and deliberately not fatal: an integration must not start failing because
    # a bookkeeping write did. Written at minute granularity so a busy key does not issue an
    # UPDATE on every single request.
    try:
        now = datetime.datetime.utcnow()
        if not record.last_used_at or (now - record.last_used_at).total_seconds() >= 60:
            record.last_used_at = now
            db.session.commit()
    except Exception:
        db.session.rollback()

    # The creator's row is only used to satisfy AdminScope's shape; nothing reads its
    # permissions. The key's own company is what decides reach, so a key does not gain or
    # lose access when the person who created it does.
    owner = User.query.get(record.created_by) if record.created_by else None
    scope = AdminScope(owner, [record.company_id], is_super=False)

    return ApiKeyPrincipal(record, scope, remaining)


def require_scopes(*scopes):
    """Build a dependency that authenticates AND demands specific scopes.

    Used as the route's own dependency so the scope requirement sits in the signature, where
    it is visible next to the path, rather than as a call somewhere in the body that a
    reader has to find and a writer can forget.
    """

    def dependency(principal: ApiKeyPrincipal = Depends(api_key_auth)) -> ApiKeyPrincipal:
        principal.require(*scopes)
        return principal

    return dependency
